### ISSUE TITLE
Is it possible to have an option that skips loading all automatical lenses?

### ISSUE THREAD

**Issue by adamryczkowski** [paluh/ansible-augeas#10]
When used together with the `transform` parameter, it would speed up each augeas invocation few orders of magnitude; on my system every run of augeas has about 1 second upfront time penalty(!). 

-----

I've took a look on the `/usr/lib/python2.7/dist-packages/augeas.py` to see if I can patch your code myself. I am a novice in Python and maybe I've missed something, but from what I've seen these python bindings don't seem to allow this kind of optimization. Can you confirm this?

**Comment by raphink** [comment]
You need to pass the `NO_MODL_AUTOLOAD` flag when initiating the augeas object, and then call `transform` and `load`. The augeas puppet type does that dynamically, see https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/augeas/augeas.rb#L154

**Comment by paluh** [comment]
> Can you confirm this?

I've checked it too and it seems that you are right. I think that we can't do anything simple to speedup performance of module loading - I've checked original augeas C librabary API and python binding follows it directly.

In general, as @raphink pointed out (thanks for suggestion!), it is possible to follow puppet strategy and extend this module API with some context parameter (if I understand what is done here: https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/augeas/augeas.rb#L176) and drop all `/augeas/load` children which not match given value and then load modules... Sorry, but I don't have any more time for changes in this module now, but you are welcome to send me pull requests ;-)

I've also noticed that I should make `load` an explicit command and not call it internally, because it can destroy all unsaved modifications. User should decide when he wants to load files. @adamryczkowski  you should modify your playbooks according to latest changes - look into `transform` example in README.

**Comment by paluh** [comment]
This issue has been partially solved by new `file` and `lens` parameters. They can be used only with `command` (not with `commands`) and they allow to point exact `lens` for given `file`. In this mode `NO_MODL_AUTOLOAD` is used to speed up processing.

I'm closing this issue with hope that this solution can work for your specific cases.
