### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by liquidat** [paluh/ansible-augeas#19]
Hej hej, have you thought about incorporating the module with Ansible upstream? It would be a great place to bring it more attention and to improve it further on.

**Comment by abedwardsw** [comment]
my only one comment is that it's a little bit of a pain that you rely on the python augeas library, I am managing a large environment of a variety of different servers/platforms, they all have the augeas binary package available, but not quite as easy to get the python library as it's not native on a lot of platforms (rpm, deb etc) and pip isn't something we typically use for a variety of reasons.   Just a thought, but wonder if including the augeas python library with your ansible library might make it easier for people to adopt your lib.    It might also help with your PR as that was one of the comments from the Ansible team as well.      I would also like to use your library but would really like to see it upstream as well.   thanks for the contribution.

**Comment by tpo** [comment]
I have not tried to use ansible-augeas yet, but I'd be very interested in its approach.

My experience with ansible has shown me that working with templates as argued by @mpdehaan in ansible/ansible#2381 is a "broken as designed" approach. It *does* work for simple cases but it in particular works very poorly with `sshd_config`. The reason is, that sshd's config file keeps changing from ssh release to ssh release from distro release to distro release and from distro to distro. The result is either a "turing complete" template with loads of hyper complex logic in it or otherwise a combinatorial explosion of config templates (for each ssh release, for each distro release, for each distro, for all the options you (sometimes) want to set etc.).

So I think the approach to parse and "understand" a config file, and then to just set the options you want/need to, as augeas aims to do, is the right way to go.

The situation wrt upstreaming modules has recently changed in that ansible as an organisation doesn't want to increase modules included in ansible proper, but is splitting them out into separately maintained [collections](https://github.com/ansible-collections). So this could be a moment to reconsider upstreaming ansible-augeas into a collection.

Wrt to how hard that would be:
 
@abedwardsw wrote:

> my only one comment is that it's a little bit of a pain that you rely on the python augeas library, I am managing a large environment of a variety of different servers/platforms, they all have the augeas binary package available, but not quite as easy to get the python library as it's not native on a lot of platforms (rpm, deb etc)

Both in Ubuntu and on Debian there's a package `python-augeas` (I can't check for RedHat since their package browser seems to live be behind the Great Red Hat Firewall only). So as far as I understand, no `pip` manipulation is necessary under these platforms any more? So all that would be required would be:

    - name: install augeas
       apt: pkg=python-augeas

and

    ansible-galaxy role install augeas

unfortunately the later yields:

    $ ansible-galaxy role install augeas
    - downloading role 'augeas', owned by 
    [WARNING]: - augeas was NOT installed successfully: None (HTTP Code: 400, Message: Bad Request)
    ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by mpdehaan** [comment]
I really don’t need the @ here

On Wed, Aug 5, 2020, at 11:25 AM, Tomáš Pospíšek wrote:
> 

> I have not tried to use ansible-augeas yet, but I'd be very interested in its approach.

> My experience with ansible has shown me that working with templates as argued by @mpdehaan <https://github.com/mpdehaan> in ansible/ansible#2381 <https://github.com/ansible/ansible/pull/2381> is a "broken as designed" approach. It *does* work for simple cases but it in particular works very poorly with `sshd_config`. The reason is, that sshd's config file keeps changing from ssh release to ssh release from distro release to distro release and from distro to distro. The result is either a "turing complete" template with loads of hyper complex logic in it or otherwise a combinatorial explosion of config templates (for each ssh release, for each distro release, for each distro, for all the options you (sometimes) want to set etc.).

> So I think the approach to parse and "understand" a config file, and then to just set the options you want/need to, as augeas aims to do, is the right way to go.

> The situation wrt upstreaming modules has recently changed in that ansible as an organisation doesn't want to increase modules included in ansible proper, but is splitting them out into separately maintained collections <https://github.com/ansible-collections>. So this could be a moment to reconsider upstreaming ansible-augeas into a collection.

> Wrt to how hard that would be:

> @abedwardsw <https://github.com/abedwardsw> wrote:

>> my only one comment is that it's a little bit of a pain that you rely on the python augeas library, I am managing a large environment of a variety of different servers/platforms, they all have the augeas binary package available, but not quite as easy to get the python library as it's not native on a lot of platforms (rpm, deb etc)

> Both in Ubuntu and on Debian there's a package `python-augeas` (I can't check for RedHat since their package browser seems to live be behind the Great Red Hat Firewall only). So as far as I understand, no `pip` manipulation is necessary under these platforms any more? So all that would be required would be:

> `- name: install augeas
   apt: pkg=python-augeas
`
> and

> `ansible-galaxy role install augeas
`
> unfortunately the later yields:

> `$ ansible-galaxy role install augeas
- downloading role 'augeas', owned by 
[WARNING]: - augeas was NOT installed successfully: None (HTTP Code: 400, Message: Bad Request)
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
`

**Comment by tpo** [comment]
> I really don’t need the @ here

sorry

**Comment by liquidat** [comment]
Closing this request, since Ansible switched to collections and thus the distribution method of plugins is now different - no need to bring this upstream anymore.

**Comment by drzraf** [comment]
brought it up again: https://github.com/ansible-collections/community.general/issues/12514
